{
  pkgs,
  lib,
  config,
  inputs,
  ...
}: let
  bottles = bottles.override {removeWarningPopup = true;};
  pks = with pkgs; [
    # keep-sorted start
    # bitwarden-cli
    # bitwarden-desktop
    # bitwarden-menu
    _86Box-with-roms
    angryipscanner
    antares
    arduino-ide
    bazaar
    bluebubbles
    bluetooth_battery
    # inputs.zephyr-nix.packages."${pkgs.stdenv.hostPlatform.system}".sdkFull
    # inputs.zephyr-nix.packages."${pkgs.stdenv.hostPlatform.system}".hosttools
    bottles
    boxbuddy
    buttermanager
    cameractrls
    celestia
    chromium
    clipqr
    clutter
    code-nautilus
    coppwr
    crosspipe
    custom.actioneer
    custom.butler
    custom.denon-control
    custom.distrib-dl
    custom.gtk-meshtastic-client
    custom.letters
    custom.manuals
    custom.netsleuth
    custom.qefi-entry-manager
    custom.remarkable-cups
    custom.retro-adsb-radar
    custom.rust-conn
    custom.toolblex
    custom.usbguard-gnome
    custom.wifiman
    cutter
    darktable
    davinci-resolve
    ddrescue
    ddrescueview
    ddrutility
    degate
    digiham
    digikam
    digital
    discordo
    distroshelf
    dmenu
    dmidecode
    dosbox-x
    doublecmd
    dsview
    easyeffects
    effitask
    # esp-idf-full
    esptool
    f1viewer
    file-roller
    filezilla
    flamp
    fldigi
    fllog
    font-manager
    fractal
    gdm-settings
    ghex
    glabels-qt
    gnomecast
    go-chromecast
    gotop
    gparted
    gphoto2
    gphoto2fs
    grsync
    gt
    gtk-engine-murrine
    guvcview
    handbrake
    httpie-desktop
    i2c-tools
    ida-free
    imsprog
    inputs.picoforge.packages."${pkgs.stdenv.hostPlatform.system}".default
    inspector
    intel-gpu-tools
    inxi
    ipmiview
    jetbrains-toolbox
    kdePackages.kdenlive
    kicad
    ktailctl
    labelle
    libGL
    libGLU
    libimobiledevice
    libratbag
    librepods
    libsmbios
    linssid
    meld
    mesa-demos
    mission-center
    mixxx
    nautilus
    nautilus-python
    neohtop
    netpeek
    noti
    nrf-command-line-tools
    nrf5-sdk
    nrfconnect
    nrfconnect-bluetooth-low-energy
    nrfutil
    nvramtool
    onioncircuits
    onionshare-gui
    opendrop
    openloco
    openra
    openrct2
    openrisk
    # openrw
    openswitcher
    pavucontrol
    pdfarranger
    pika-backup
    piper
    platformio
    # plex-desktop
    plexamp
    pods
    powerjoular
    powerstat
    powertop
    pwvucontrol
    python312Packages.pyclip
    qFlipper
    qdirstat
    qjournalctl
    # qradiolink
    rmview
    rpi-imager
    rpiboot
    rtfm
    saleae-logic-2
    satellite
    sdrpp
    segger-jlink
    segger-ozone
    serial-studio
    smuview
    solaar
    spi-tools
    # solana-cli
    spotify
    sqlitebrowser
    sublime-merge
    sway-launcher-desktop
    synology-drive-client
    the-powder-toy
    thonny
    tpmmanager
    transmission-remote-gtk
    tremotesf
    turtle
    typesetter
    ulauncher
    usbview
    uvccapture
    uvcdynctrl
    vial
    vlc
    vsce
    vte-gtk4
    webcamize
    webcamoid
    wine-wayland
    wiremix
    wl-clipboard
    wsjtx
    xdg-utils
    xdgmenumaker
    xdiskusage
    xdotool
    xpipe
    xplanet
    yelp
    zed-editor
    zenmap
    # keep-sorted end
  ];
  cfg = config.gui.desktop;
in {
  config = lib.mkIf (cfg.enable) {
    environment.systemPackages = pks;
  };
}
