always-allow-substitutes = true
bash-prompt-prefix = (nix:$name)\040
eval-cores = 0
extra-nix-path = nixpkgs=flake:https://flakehub.com/f/DeterminateSystems/nixpkgs-weekly/*.tar.gz
max-jobs = auto
lazy-trees = true

!include nix.custom.conf

extra-experimental-features = nix-command flakes
netrc-file = /nix/var/determinate/netrc
extra-substituters = https://install.determinate.systems
extra-trusted-substituters = https://cache.flakehub.com https://install.determinate.systems
extra-trusted-public-keys = cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= cache.flakehub.com-4:Asi8qIv291s0aYLyH6IOnr5Kf6+OF14WVjkE6t3xMio= cache.flakehub.com-5:zB96CRl$
upgrade-nix-store-path-url = https://install.determinate.systems/determinate-nix/stable/fallback-paths.nix
ssl-cert-file = /etc/nix/macos-keychain.crt

















