# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "swift-adwaita" = "sha256-iMYKQepOFXz6behxNksiHbAWy0mdbxTj0s3EfVt+zO0=";
    "swift-cmark" = "sha256-0pyZ5yQRsbiKwz2XT8N6dMwCLcmM28qQOrxHcV6uH7g=";
    "swift-markdown" = "sha256-/lDRUjcMmNTqvwdPXisy/LR4FxwFeqx148M4fKoCXu0=";
  };
}
