{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.apps.netdata;
  cfgServer = cfg.server;

  guid = "059640A0-AB30-4DA2-AE4D-1AE21B5CF71D";
  server = "silver-star.ling-lizard.ts.net:19999";
in {
  options.apps.netdata = {
    enable =
      lib.mkEnableOption "netdata"
      // {
        default = true;
      };

    server.enable = lib.mkEnableOption "netdata server";
  };

  config = lib.mkIf cfg.enable {
    age.secrets = {
      netdata = {
        rekeyFile = ../../secrets/netdata.age;
        # mode = "600";
        owner = "netdata";
        group = "netdata";
      };
      netdata-stream-conf = {
        rekeyFile = ./stream.conf.age;
        owner = "netdata";
        group = "netdata";
      };
    };

    # security.sudo = {
    #   extraRules = [
    #     # netdata ALL=(root) NOPASSWORD: nvme
    #     {
    #       commands = [
    #         {
    #           command = "${pkgs.nvme-cli}/bin/nvme";
    #           options = ["NOPASSWD"];
    #         }
    #       ];
    #       users = [
    #         "netdata"
    #         "tomas"
    #       ];
    #     }
    #   ];
    # };

    services.netdata = {
      enable = lib.mkDefault true;

      package = pkgs.netdataCloud.override {
        withCloudUi = true;
        withNetworkViewer = true;
        withConnPrometheus = true;
        withConnPubSub = true;
        withNdsudo = true; # false;
      };
      extraNdsudoPackages = [
        pkgs.smartmontools
        pkgs.nvme-cli
      ];

      # claimTokenFile = config.age.secrets."netdata".path;

      python = {
        enable = true;
        recommendedPythonPackages = true;
      };
      config = {
        global = {
          "debug log" = "none";
          "access log" = "none";
          "error log" = "syslog";
        };

        health = {
          enabled = "yes";
          "enabled alarms" = "*";
        };

        db = {
          mode =
            if cfgServer.enable
            then "dbengine"
            else "ram";
          "storage tiers" =
            #lib.mkIf cfgServer.enable
            3;

          # Tier 0, per second data. Set to 0 for no limit.
          "dbengine tier 0 retention size" =
            #lib.mkIf cfgServer.enable
            "1GiB";
          "dbengine tier 0 retention time" =
            #lib.mkIf cfgServer.enable
            "14d";

          # Tier 1, per minute data. Set to 0 for no limit.
          "dbengine tier 1 retention size" =
            #lib.mkIf cfgServer.enable
            "1GiB";
          "dbengine tier 1 retention time" =
            #lib.mkIf cfgServer.enable
            "3mo";

          # Tier 2, per hour data. Set to 0 for no limit.
          "dbengine tier 2 retention size" =
            #lib.mkIf cfgServer.enable
            "1GiB";
          "dbengine tier 2 retention time" =
            #lib.mkIf cfgServer.enable
            "2y";
        };

        plugins = {};

        registry =
          if cfgServer.enable
          then {
            enabled = "yes";
            "registry to announce" = server;
            "allow from" = "*";
          }
          else {
            enabled = "no";
            "registry to announce" = server;
          };

        web = {
          # Allow only localhost connections
          "allow connections from" = "localhost 100.* *.ling-lizard.ts.net";

          # "ssl key" = config.proxy-services.crt.key;
          # "ssl certificate" = config.proxy-services.crt.crt;
          mode =
            if cfgServer.enable
            then "static-threaded"
            else "none";
        };
      };

      configDir = {
        "stream.conf" = pkgs.writeText "stream.conf" (
          if cfgServer.enable
          then ''
            [${guid}]
            # Accept metrics streaming from other Agents with the specified API key
            enabled = yes
            allow from = *
            db = dbengine
          ''
          else ''
            [stream]
            # Stream metrics to another Netdata
            enabled = yes
            # The IP and PORT of the parent
            destination = ${server} #:SSL
            # The shared API key, generated by uuidgen
            api key = ${guid}
          ''
        );
        "health.d/systemdunits.conf" = pkgs.fetchurl {
          url = "https://github.com/netdata/netdata/raw/refs/heads/master/src/health/health.d/systemdunits.conf";
          sha256 = "sha256-7zYRWagi5NY32llWbadTPQsPbhnTem/ES4gIHMnvOec=";
        };
        "health_alarm_notify.conf" = pkgs.writeText "health_alarm_notify.conf" ''
          SEND_NTFY="YES"
          DEFAULT_RECIPIENT_NTFY="https://ntfy.sh/tomasharkema-nixos"
        '';
        "go.d/docker.conf" = pkgs.writeText "docker.conf" ''
          jobs:
            - name: local
              address: 'unix:///var/run/docker.sock'
        '';
        "go.d/systemdunits.conf" = pkgs.writeText "systemdunits.conf" ''
          autodetection_retry: 30
          collect_unit_files: true
          jobs:
          - name: service-units
            include:
              - '*'
        '';
        "go.d/ethtool.conf" = pkgs.writeText "ethtool.conf" ''
          update_every: 10
        '';
      };
    };
  };
}
