{
  inputs,
  options,
  config,
  pkgs,
  lib,
  system,
  ...
}:
with lib;
with lib.custom; let
  cfg = config.custom.nix;
in {
  imports = [
    # inputs.agenix.darwinModules.default
  ];

  options = {
    custom.nix = with types; {
      enable = mkBoolOpt true "Whether or not to manage nix configuration.";
      package = mkOpt package pkgs.nix "Which nix package to use.";
    };
    gui = {
      enable = mkBoolOpt false "Whether or not to manage nix configuration.";
      gnome.enable = mkBoolOpt false "Whether or not to manage nix configuration.";
    };
  };

  config = {
    environment.systemPackages = with pkgs; [
      deploy-rs
      nixfmt
      nix-prefetch-git
      nil
      flake-checker
      direnv
      # attic
      alejandra
      # inputs.alejandra.packages.${system}.default
      nix-output-monitor
      nixpkgs-fmt
      nerd-font-patcher
    ];
    traits.developer.enable = true;

    services.nix-daemon.enable = true;

    # age.secrets."op" = {
    #   file = ../../../secrets/op.age;
    #   mode = "744";
    #   # path = "/home/tomas/.google_authenticator";
    #   # owner = "tomas";
    #   # group = "tomas";
    # };

    nix = let
      users = ["root" "tomas"];
    in {
      # package = pkgs.nixUnstable;

      linux-builder = {
        enable = true;
        ephemeral = true;
        maxJobs = 4;
        config = {
          virtualisation = {
            # rosetta.enable = true;
            darwin-builder = {
              diskSize = 30 * 1024;
              memorySize = 4 * 1024;
            };
            cores = 4;
          };
        };
      };

      settings = {
        http-connections = 50;
        warn-dirty = false;
        log-lines = 50;

        # Large builds apparently fail due to an issue with darwin:
        # https://github.com/NixOS/nix/issues/4119
        sandbox = false;

        # This appears to break on darwin
        # https://github.com/NixOS/nix/issues/7273
        auto-optimise-store = false;

        allow-import-from-derivation = true;

        # trusted-users = users;
        allowed-users = users;

        trusted-users = ["root" "tomas"];

        # NOTE: This configuration is generated by nix-installer so I'm adding it here in
        # case it becomes important.
        #extra-nix-path = "nixpkgs=flake:nixpkgs";
        build-users-group = "nixbld";

        # netrc-file = "/etc/nix/netrc";

        substituters = [
          "https://nix-gaming.cachix.org"
          "https://nix-community.cachix.org"
          "https://cache.nixos.org/"
          "https://blue-fire.ling-lizard.ts.net/attic/tomas/"
          "https://devenv.cachix.org"
          "https://tomasharkema.cachix.org"
        ];

        trusted-public-keys = [
          "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
          "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
          "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw="
          "peerix-tomas-1:OBFTUNI1LIezxoFStcRyCHKi2PHExoIcZA0Mfq/4uJA="
          "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw="
          "tomas:qzaaV24nfgwcarekICaYr2c9ZBFDQnvvydOywbwAeys="
          "nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4="
          "tomasharkema.cachix.org-1:BV3Sv3qGZ0bcybPFeigwKoxnpj/NBAFYHq9FMO1XgH4="
        ];

        # binaryCaches = ["https://cache.nixos.org"];
      };
      # // (lib.optionalAttrs config.plusultra.tools.direnv.enable {
      #   keep-outputs = true;
      #   keep-derivations = true;
      # });

      gc = {
        automatic = true;
        interval = {Day = 1;};
        options = "--delete-older-than 14d";
        user = "tomas";
      };

      # flake-utils-plus
      generateRegistryFromInputs = true;
      generateNixPathFromInputs = true;
      linkInputs = true;
    };
  };
}
