# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{lib, ...}: {
  imports = [./disk-config.nix {_module.args.disks = ["/dev/sda"];}];

  boot.initrd.availableKernelModules = ["sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  #   fileSystems."/" = {
  #     device = "/dev/disk/by-uuid/2aa478a5-ccd9-4023-95a1-daecfd13f18b";
  #     fsType = "ext4";
  #   };

  #   fileSystems."/boot" = {
  #     device = "/dev/disk/by-uuid/888B-3762";
  #     fsType = "vfat";
  #   };

  #   swapDevices =
  #     [{ device = "/dev/disk/by-uuid/6ebeefbf-4ba0-44f7-9797-e616414e646e"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.hypervGuest.enable = true;
}
