# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet {
    pname = "AtkSharp";
    version = "3.24.24.34";
    sha256 = "1jn1vgi9xm0jp7769k6sbdi8d273kigjrsh93i6s4c03hqxv7cqs";
  })
  (fetchNuGet {
    pname = "CairoSharp";
    version = "3.24.24.34";
    sha256 = "0pydn1k0cam1gclg9sc1sbnmbyzh28qlc5qanyxcylwghink3kgz";
  })
  (fetchNuGet {
    pname = "Eto.Forms";
    version = "2.7.0";
    sha256 = "1k8m9gfdcvqxndmggxml21hy51wjcq8ya5lnn986ks4pfca7245b";
  })
  (fetchNuGet {
    pname = "Eto.Platform.Gtk";
    version = "2.7.0";
    sha256 = "08w5mr49cnq7bn0060z4dg57jqd1qy1yyjdbjla9h64swb0fgdff";
  })
  (fetchNuGet {
    pname = "GdkSharp";
    version = "3.24.24.34";
    sha256 = "0r0x0yib7chwsyrbpvicrfwldwqx5lyqq4p86zaxpmzd6zdaj0x5";
  })
  (fetchNuGet {
    pname = "GioSharp";
    version = "3.24.24.34";
    sha256 = "02hxvgjd4w9jpzbkk7qf9q9bkvyp5hfzwxfqp10vg5lpl9yl3xpx";
  })
  (fetchNuGet {
    pname = "GLibSharp";
    version = "3.24.24.34";
    sha256 = "0kvp033fgdwc8p2abfp5z9pzq66cvwbnjfvr4v4bkpy5s5h181kq";
  })
  (fetchNuGet {
    pname = "GtkSharp";
    version = "3.24.24.34";
    sha256 = "0028hzmmqyfx87qqmaf9cgb5psn7gkbmqvixcid67x1d6mzxjicb";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "6.0.0";
    sha256 = "15gqy2m14fdlvy1g59207h5kisznm355kbw010gy19vh47z8gpz3";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    sha256 = "08vh1r12g6ykjygq5d3vq09zylgb84l63k49jc4v8faw9g93iqqm";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.3";
    sha256 = "1fn9fxppfcg4jgypp2pmrpr6awl3qz1xmnri0cygpkwvyx27df1y";
  })
  (fetchNuGet {
    pname = "PangoSharp";
    version = "3.24.24.34";
    sha256 = "1r0h14cklglfpv1lhv93cxmzi2w7d5s03gzpq3j5dmrz43flg9zw";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.1";
    sha256 = "04kb1mdrlcixj9zh1xdi5as0k0qi8byr5mi3p3jcxx72qz93s2y3";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "5.0.0";
    sha256 = "021h7x98lblq9avm1bgpa4i31c2kgsa7zn4sqhxf39g087ar756j";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.4";
    sha256 = "14gbbs22mcxwggn0fcfs1b062521azb9fbb7c113x0mq6dzq9h6y";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.5.0";
    sha256 = "1kzrj37yzawf1b19jq0253rcs8hsq1l2q8g69d7ipnhzb0h97m59";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    sha256 = "0qm741kh4rh57wky16sq4m0v05fxmkjjr87krycf5vp9f0zbahbc";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "6.0.0";
    sha256 = "06n9ql3fmhpjl32g3492sj181zjml5dlcc5l76xq2h38c4f87sai";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.4";
    sha256 = "19ygfw7b6rasjk0v6bdra85a5rh1qq4q2wgrclzvcrps66lcv5w1";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    sha256 = "0y6ncasgfcgnjrhynaf0lwpkpkmv4a07sswwkwbwb5h7riisj153";
  })
]
