{
  pkgs,
  lib,
  config,
  inputs,
  ...
}: {
  config = {
    environment.systemPackages =
      (with pkgs; [
        kitty.terminfo
        wezterm.terminfo
        nix-alien
        curlftpfs
        # apfs-fuse
        # apfsprogs
        # bat-extras.batgrep
        # fancy-motd
        # jupyter
        # lz4
        # mkchromecast
        # nix-switcher # : needs github auth
        # wavemon
        agenix-rekey
        aide
        apt-dater
        archivemount
        bandwhich
        bash
        bashmount
        bat-extras.batdiff
        bat-extras.batman
        bat-extras.batpipe
        bat-extras.batwatch
        binwalk
        bmc-tools
        bmon
        bridge-utils
        caligula
        castnow
        catt
        ccrypt
        chunkfs
        cksfv
        clang-tools
        clex
        cmake
        colorized-logs
        compsize
        config.boot.kernelPackages.iio-utils
        cryptsetup # needed for dm-crypt volumes
        ctop
        curl
        custom.discovery-rs
        custom.flightmon
        custom.meshtui
        custom.partclone-utils
        custom.radar
        custom.sshm
        custom.wikiman
        custom.zide
        custom.ssh-proxy-agent
        custom.menu
        custom.ssm
        custom.tailscale-tui
        custom.sshed
        # rmfuse
        cutecom
        ddrescue
        devcontainer
        devtodo
        dfrs
        distrobox
        distrobox-tui
        dry
        duc
        efibootmgr
        efivar
        ethtool
        # fbterm
        fcast-receiver
        freeipmi
        fuse
        fuse3
        gdb
        gdbgui
        gdu
        gensio
        ghostty
        git
        git
        glog
        glogg
        gnumake
        gnupg
        gpio-utils
        gpsd
        gptfdisk
        hdparm
        helix
        hextazy
        htmlq
        hueadm
        hw-probe
        i2c-tools
        ifuse
        imv
        ipcalc
        ipmitool
        ipmiutil
        iptraf-ng
        isd
        kexec-tools
        kmon
        lazydocker
        ldapdomaindump
        libftdi
        libftdi1
        libgpiod
        libheif
        libnotify
        libsecret
        libusb1
        lm_sensors
        lnav
        lorri
        lrzsz
        lshw
        mbuffer
        minio-client
        more
        mpremote
        mpv
        ms-sys # for writing Microsoft boot sectors / MBRs
        ncdu
        nethogs
        netop
        netproc
        netscanner
        networkmanagerapplet
        nfs-utils
        nil
        ninja
        nix-btm
        nix-check-deps
        nix-playground
        nix-search-cli
        nix-search-tv
        nix-top
        nixd
        nixos-anywhere
        nixos-facter
        nmap
        nmon
        ntfs3g
        ntfy
        ntfy-sh
        nvchecker
        nvme-cli
        nyaa
        onionshare
        openipmi
        openldap
        openocd
        openseachest
        opensoundmeter
        oterm
        p7zip
        pamix
        pamixer
        parted
        pciutils
        pciutils
        picotool
        picotool
        pigz
        piratebay
        pkgs.custom.nix-helpers
        play
        ponymix
        pulsemixer
        pv
        pwgen
        python313Packages.pyftdi
        python3Packages.pip
        python3Packages.uv
        redfishtool
        regname
        rsbkb
        rtop
        s-tui
        screen
        sdparm
        ser2net
        sigrok-cli
        silenthound
        smartmontools
        socat
        socklog
        squashfs-tools-ng
        squashfsTools
        ssh-import-id
        ssh-tools
        ssh-tools
        sshfs
        sshfs-fuse
        sshportal
        starship
        strace
        swapview
        sysstat
        systemctl-tui
        systeroid
        sysz
        tailspin
        tcpdump
        tcptrack
        termshark
        testdisk # useful for repairing boot problems
        tio
        tiptop
        tparted
        tpm-tools
        tran
        treecat
        tshark
        tsui
        ttmkfdir
        ttop
        tydra
        unzip
        update-nix-fetchgit
        updatecli
        urjtag
        usbredir
        usbutils
        usbutils
        usermount
        uv
        viddy
        vim
        watchlog
        websocat
        wget
        wget
        whatfiles
        wmctrl
        wol
        wtfutil
        xterm
        xxd
        zathura
        zip
        zstd
      ])
      ++ (lib.optionals pkgs.stdenv.isx86_64 (
        with pkgs; [
          cmospwd
          dmidecode
          fwupd
          fwupd-efi
          gnutls
          ipmicfg
          libsmbios
          meshtastic-fix
          micropython
          refind
          spectre-meltdown-checker
          uefisettings
        ]
      ));
  };
}
