# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "swift-system" = "0402hkx2q2dv27gccnn8ma79ngvwiwzkhcv4zlcdldmy6cgi0px7";
    "swift-tools-support-core" = "0dygv5brz30km0kl3wwaqj6m5z650d608x4hwh6ka48v4mk5w8hh";
  };
}
