{
  pkgs,
  inputs,
  ...
}:
with pkgs; [
  inputs.agenix.packages.${system}.default
  inputs.alejandra.defaultPackage.${system}
  inputs.nil.packages.${system}.default
  inputs.nix-cache-watcher.packages.${system}.nix-cache-watcher
  inputs.nixpkgs-lint.packages.${system}.default
  inputs.statix.packages.${system}.statix
  manix
  nix
  nix-init
  nix-output-monitor
  nix-serve
  nix-tree
  nixci
  nixd
  nixpkgs-fmt
  nurl
]
