{
  lib,
  stdenv,
  fetchFromGitHub,
  buildGoModule,
}:
buildGoModule {
  pname = "netconsoled";
  version = "unstable-2017-11-29";

  src = fetchFromGitHub {
    owner = "tomasharkema";
    repo = "netconsoled";
    rev = "37334f2d132a1ad279305dfd03907033c0b31f23";
    hash = "sha256-8LsgLww38uqTxKIWTjprSLfTJlbQGCSxU4rBjmfszis=";
  };
  vendorHash = null;
  meta = {
    description = "Command netconsoled provides a server that can receive and process logs generated by the netconsole Linux kernel module. MIT Licensed";
    homepage = "https://github.com/mdlayher/netconsoled";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [];
    mainProgram = "netconsoled";
    platforms = lib.platforms.all;
  };
}
