name: "check"
on:
  push:

concurrency:
  group: "check-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix run "https://flakehub.com/f/DeterminateSystems/flake-checker/0.1.17.tar.gz"
      - run: nix flake check --accept-flake-config
      # - run: nom build '.#nixosConfigurations.blue-fire.config.formats.qcow' --out-link ./out/bluefire.qcow2
      # - run: NIX_SHOW_STATS=1 NIX_COUNT_CALLS=1 nix flake check
  # iso:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cachix/install-nix-action@v23
  #       with:
  #         nix_path: nixpkgs=channel:nixos-23.11
  #     - run: nix develop -c nix build '.#installiso' --verbose
  # encaladus:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cachix/install-nix-action@v23
  #       with:
  #         nix_path: nixpkgs=channel:nixos-23.11
  #     - run: nix develop -c nix build .#nixosConfigurations."enzian".config.system.build.toplevel --verbose
  # blue-fire:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cachix/install-nix-action@v23
  #       with:
  #         nix_path: nixpkgs=channel:nixos-23.11
  #     - run: nix develop -c nix build .#nixosConfigurations."blue-fire".config.system.build.toplevel --verbose
  # pegasus:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cachix/install-nix-action@v23
  #       with:
  #         nix_path: nixpkgs=channel:nixos-23.11
  #     - run: nix develop -c nix build .#images.aarch64-darwin.pegasus --verbose
