name: "check"
on:
  push:

concurrency:
  group: "check-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    strategy:
      matrix:
        os: [self-hosted, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v12
        with:
          name: deadnix
      - run: nix run "https://flakehub.com/f/DeterminateSystems/flake-checker/0.1.17.tar.gz"
      - run: nix flake check --accept-flake-config
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "tomasharkema/nix-config"
          rolling: true
          visibility: "unlisted"
      - uses: astro/deadnix-action@main
