name: "check"
on:
  push:

jobs:
  check:
    strategy:
      matrix:
        os: [self-hosted, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    concurrency:
      group: "check-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.os }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v12
        with:
          name: tomasharkema
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: cachix/cachix-action@v12
        with:
          name: deadnix
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix run "https://flakehub.com/f/DeterminateSystems/flake-checker/0.1.17.tar.gz"
      - run: nix flake check --accept-flake-config
      - uses: astro/deadnix-action@main
      - run: nix build '.#images.blue-fire-slim'
      - run: nix build '.#images.blue-fire'
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "tomasharkema/nix-config"
          rolling: true
          visibility: "unlisted"
