name: "deadnix"
on:
  push:

concurrency:
  group: "deadnix-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  deadnix:
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v12
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
