name: "ISO"
on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  iso:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix build '.#installiso'
      - run: nix build .#nixosConfigurations."enceladus".config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | attic push tomas:harkema --stdin
  encaladus:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix build .#nixosConfigurations."enceladus".config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | attic push tomas:harkema --stdin
  supermicro:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix build .#nixosConfigurations."supermicro".config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | attic push tomas:harkema --stdin
  raspbii4:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix build .#images.aarch64-darwin.raspbii4 --json | jq -r '.[].outputs | to_entries[].value' | attic push tomas:harkema --stdin
