name: "ISO"
on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v12
        with:
          name: tomasharkema
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build '.#installiso'
      - uses: actions/upload-artifact@v3
        with:
          name: nixos-tomas.iso
          path: ./result/iso/*.iso
      # - run: nix build .#darwinConfigurations.MacBook-Pro-van-Tomas.system --json | jq -r '.[].outputs | to_entries[].value' | cachix push tomasharkema
      # - run: nix build .#nixosConfigurations."enceladus".config.system.build.toplevel --json | jq -r '.[].outputs | to_entries[].value' | cachix push tomasharkema
