name: Nix Flake actions

on:
  pull_request:
  push:
    branches: "*"
      # - master
      # - main

jobs:
  nix-build:
    continue-on-error: true
    runs-on: "nixos"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix build -L '.#images.all' --accept-flake-config --keep-going -L --verbose
